<script>
export default {
  data() {
    return {
      isShow: false,
      opacity: 1,
    };
  },
  methods: {
    show() {
      const vm = this;
      vm.opacity = 1;
      vm.isShow = true;
    },
    hide() {
      const vm = this;
      setTimeout(function () {
        vm.opacity = 0;
        setTimeout(function () {
          vm.isShow = false;
          vm.opacity = 1;
        }, 900);
      }, 300);
    },
  },
};
</script>

<template>
  <section>
    <div
      v-show="isShow"
      class="loadingio-outer position-fixed top-0 start-0 w-100 vh-100"
      :style="{ opacity: opacity }"
      style="z-index: 999999; transition: all 0.9s ease"
    >
      <div class="position-absolute translate-middle start-50 top-50">
        <div class="loadingio-spinner-ripple-jkoucqrh5va">
          <div class="ldio-kpc4guhddbk">
            <div></div>
            <div></div>
          </div>
        </div>
      </div>
      <!-- <div
        class="position-absolute translate-middle start-50 top-50 text-center en fs-3 text-primary"
      >
        CHIC MI
      </div> -->
    </div>
  </section>
</template>

<style type="text/css">
.loadingio-outer {
  background: rgba(0, 0, 0, 1);
}

@keyframes ldio-kpc4guhddbk {
  0% {
    top: 96px;
    left: 96px;
    width: 0;
    height: 0;
    opacity: 1;
  }
  100% {
    top: 18px;
    left: 18px;
    width: 156px;
    height: 156px;
    opacity: 0;
  }
}
.ldio-kpc4guhddbk div {
  position: absolute;
  border-width: 4px;
  border-style: solid;
  opacity: 1;
  border-radius: 50%;
  animation: ldio-kpc4guhddbk 1.3157894736842106s cubic-bezier(0, 0.2, 0.8, 1)
    infinite;
}
.ldio-kpc4guhddbk div:nth-child(1) {
  border-color: #dbc60d;
  animation-delay: 0s;
}
.ldio-kpc4guhddbk div:nth-child(2) {
  border-color: #dd3526;
  animation-delay: -0.6578947368421053s;
}
.loadingio-spinner-ripple-jkoucqrh5va {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: rgba(0, 0, 0, 0);
}
.ldio-kpc4guhddbk {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-kpc4guhddbk div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
